sdk: "/home/suren/.rvm/gems/ruby-1.8.7-p334/gems/rhodes-3.0.1"
sdkversion: 3.0.1
name: NewGithubclient
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator4.3
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.newgithubclient
  BundleURLScheme: newgithubclient
wp:
  productid: 'f8c8c860-7a0b-012e-e5ae-001f16be7d14'

extensions: ["json", "another-extension"]
